### ISSUE TITLE
Using totalspineseg on CT images

### ISSUE THREAD

**Issue by ricardopizarro** [neuropoly/totalspineseg#69]
Hello,

I see in the Results section of your README, that totalspineseg can work on CT images to accurately segment the spinal cord. Is the performance with CT images the same as MR images? Would another round of training (finetuning) be required to get comparable accuracy? Or are the results much better with MRI data?  

Thank you in advance,
-Ricardo

**Comment by yw7** [comment]
Hello @ricardopizarro,

Thank you for your interest in our work!

We haven't yet validated the spinal cord segmentation of the model on CT images. If the spinal cord is not accurately visible in the original image, the model may hallucinate where it believes the spinal cord is, but it should not be trusted without quality control checks.
As mentioned in the README:
While TotalSpineSeg provides spinal cord segmentation, it is not intended to replace validated methods for cross-sectional area (CSA) analysis. The spinal cord segmentation from TotalSpineSeg has not been validated for CSA measurements, nor has it been tested on cases involving spinal cord compressions, MS lesions, or other spinal cord abnormalities. For accurate CSA analysis, we strongly recommend using the validated algorithms available in the [Spinal Cord Toolbox](https://spinalcordtoolbox.com/user_section/tutorials/segmentation.html).

Regarding your question about MRI, I believe that spinal cord segmentation in MRI will be much more accurate since the spinal cord is more clearly visible, especially with T2-weighted images where the spinal cord/CSF contrast is high.

Best regards,
Yehuda

**Comment by ricardopizarro** [comment]
Thank you for getting back to me so promptly! 
A follow up question, would totalspineseg work for segmenting the vertebrae (rather than the spinal cord) with CT images?

All the best,
-Ricardo

**Comment by yw7** [comment]
Yes! It should work as in the results section. Please follow the installation and inference instructions in the readme to get those results.

**Comment by ricardopizarro** [comment]
Great! Thank you for responding. We are working with a multi-modal dataset. 
Would totalspineseg also work on X-Ray images? 

Thanks in advance,
-Ricardo

**Comment by yw7** [comment]
No. It is only work on 3D medical images in Nifty (.nii.gz) format.
